name: devlopment-deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ master,development ]
  pull_request:
    branches: [ master,development ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name : Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env to staging
        if: endsWith(github.ref, '/development')
        run: |
          echo "ENVIRONMENT=stage" >> $GITHUB_ENV
          echo "S3_BUCKET=${{ secrets.AWS_S3_BUCKET_STAGE}}" >> $GITHUB_ENV
      - name: Set env to production
        if: endsWith(github.ref, '/master')
        run: |
          echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          echo "S3_BUCKET=${{ secrets.AWS_S3_BUCKET_PROD}}" >> $GITHUB_ENV

      #   env: 
      #     NODE_ENV: dev
      #     AWS_USERPOOLID: ${{secrets.AWS_USERPOOLID}}
      # - name: npm install
      #   run: npm install

      # Runs a set of commands using the runners shell
     
      - name: Show files
        run: | 
             ls -a
             ls -a ./BrandConfig

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}
      - run: aws s3 sync ./BrandConfig  s3://$S3_BUCKET/config/


  # aws_deployment:
  #   runs-on: ubuntu-latest
  #   name: Deploy 
  #   needs: [build]
  #   steps:
  #     - name: download artifacts
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: dist
  #     - name: deploy to s3
        
  #       uses: jakejarvis/s3-sync-action@master
  #       with:
  #         args: --acl public-read --follow-symlinks --delete
  #       env:
  #         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_REGION: ${{ secrets.AWS_REGION }}   # optional: defaults to us-east-1
  #         SOURCE_DIR: 'dist'      # optional: defaults to entire repository